# Generated by Django 5.2.8 on 2025-12-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='available_seats',
            field=models.IntegerField(default=0, verbose_name='Свободных мест'),
        ),
    ]
