# Generated by Django 5.2.8 on 2025-12-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='action',
            field=models.CharField(choices=[('created', 'Создано'), ('confirmed', 'Подтверждено'), ('confirmed_by_admin', 'Подтверждено администратором'), ('cancelled', 'Отменено'), ('cancelled_by_admin', 'Отменено администратором'), ('completed', 'Завершено'), ('modified', 'Изменено'), ('modified_by_admin', 'Изменено администратором')], max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='action_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата действия'),
        ),
    ]
