# Generated by Django 5.2.8 on 2025-12-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_booking_user_delete_bookinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_people',
            field=models.IntegerField(default=1, verbose_name='Количество человек'),
        ),
    ]
